steps:
  # ==========================================
  # PARALLEL BUILD STAGE
  # ==========================================

  # 1. Pull Backend Cache (Skipping or keeping, doesn't matter if we use --no-cache, but keeping for structure)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull Backend Cache'
    entrypoint: 'bash'
    args: ['-c', 'docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:latest || exit 0']
    waitFor: ['-'] # Starts immediately

  # 2. Build Backend Container (Tags with SHA and Latest)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args: [
      'build',
      '--no-cache',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$SHORT_SHA',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:latest',
      '--cache-from', 'europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:latest',
      '.'
    ]
    dir: 'backend'
    waitFor: ['Pull Backend Cache']

  # 3. Push Backend (Happens while we might still be preparing frontend)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    entrypoint: 'bash'
    args: ['-c', 'docker push europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$SHORT_SHA && docker push europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:latest']
    waitFor: ['Build Backend']

  # 4. Pull Frontend Cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull Frontend Cache'
    entrypoint: 'bash'
    args: ['-c', 'docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:latest || exit 0']
    waitFor: ['-'] # Starts immediately (Parallel with Backend)

  # 5. Build Frontend Container
  # Note: No build args for secrets anymore. They are injected at runtime.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$SHORT_SHA \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:latest \
          --cache-from europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:latest \
          --build-arg NEXT_PUBLIC_API_URL=https://api.perito.my \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
          .
    secretEnv: [
      'NEXT_PUBLIC_FIREBASE_API_KEY',
      'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
      'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      'NEXT_PUBLIC_FIREBASE_APP_ID',
      'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
    ]
    dir: 'frontend'
    waitFor: ['Pull Frontend Cache']

  # 6. Push Frontend Container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    entrypoint: 'bash'
    args: ['-c', 'docker push europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$SHORT_SHA && docker push europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:latest']
    waitFor: ['Build Frontend']

  # ==========================================
  # DEPLOY STAGE
  # ==========================================

  # 7. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-backend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_REGION=europe-west1'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=perito-479708:europe-west1:robotperizia-db'
      - '--set-env-vars'
      - 'DB_USER=report_user'
      - '--set-env-vars'
      - 'DB_NAME=perizia_db'
      - '--set-env-vars'
      - 'STORAGE_BUCKET_NAME=robotperizia-uploads-roberto'
      - '--set-env-vars'
      - 'CLOUD_TASKS_QUEUE_PATH=projects/$PROJECT_ID/locations/europe-west1/queues/report-processing-queue'
      # Injecting the known public URL to avoid self-update loop
      - '--set-env-vars'
      - 'BACKEND_URL=https://api.perito.my'
      - '--set-secrets'
      - '/secrets/service-account.json=firebase-creds:latest'
      - '--set-secrets'
      - 'DB_PASS=database-password:latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-secrets'
      - 'CLOUD_TASKS_SA_EMAIL=cloud-tasks-sa-email:latest'
    waitFor: ['Push Backend']

  # 8. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-frontend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      # Runtime Environment Variables
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://api.perito.my'
      # Secrets injected as environment variables
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=next-public-firebase-api-key:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=next-public-firebase-auth-domain:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=next-public-firebase-project-id:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=next-public-firebase-storage-bucket:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=next-public-firebase-messaging-sender-id:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=next-public-firebase-app-id:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=next-public-firebase-measurement-id:latest'
    waitFor: ['Push Frontend']

# Define Secrets
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-api-key/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-auth-domain/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-project-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-storage-bucket/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-messaging-sender-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-app-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-measurement-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'


options:
  logging: CLOUD_LOGGING_ONLY
