steps:
  # 1. Pull Backend Cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/robotperizia-backend:latest || exit 0']

  # 2. Build Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/robotperizia-backend:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/robotperizia-backend:latest',
      '.'
    ]
    dir: 'backend'

  # 3. Push Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/robotperizia-backend:latest']

  # 4. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/robotperizia-backend:latest'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_REGION=europe-west1'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=perito-479708:europe-west1:robotperizia-db'
      - '--set-env-vars'
      - 'DB_USER=report_user'
      - '--set-env-vars'
      - 'DB_NAME=perizia_db'
      - '--set-env-vars'
      - 'STORAGE_BUCKET_NAME=robotperizia-uploads-roberto'
      - '--set-env-vars'
      - 'CLOUD_TASKS_QUEUE_PATH=projects/$PROJECT_ID/locations/europe-west1/queues/report-processing-queue'
      - '--set-secrets'
      - '/secrets/service-account.json=firebase-creds:latest'
      - '--set-secrets'
      - 'DB_PASS=database-password:latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-secrets'
      - 'CLOUD_TASKS_SA_EMAIL=cloud-tasks-sa-email:latest'

  # 5. Get Backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run services describe robotperizia-backend --platform managed --region europe-west1 --format 'value(status.url)' > /workspace/backend_url.txt
        # Force HTTPS: Replace http:// with https://, or prepend https:// if missing scheme
        sed -i 's|^http://|https://|' /workspace/backend_url.txt
        echo "Backend URL: $(cat /workspace/backend_url.txt)"
  
  # 5.5 Update Backend with its own URL (Fix for Ouroboros Configuration Loop)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run services update robotperizia-backend \
          --region europe-west1 \
          --update-env-vars BACKEND_URL=$(cat /workspace/backend_url.txt)

  # 6. Pull Frontend Cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/robotperizia-frontend:latest || exit 0']

  # 7. Build Frontend Container (Injecting Backend URL + Secrets)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    secretEnv:
      - NEXT_PUBLIC_FIREBASE_API_KEY
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_FIREBASE_APP_ID
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    args:
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/robotperizia-frontend:latest \
        --cache-from gcr.io/$PROJECT_ID/robotperizia-frontend:latest \
        --build-arg NEXT_PUBLIC_API_URL=$(cat /workspace/backend_url.txt) \
        --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY \
        --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
        --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
        --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
        .
    dir: 'frontend'

  # 8. Push Frontend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/robotperizia-frontend:latest']

  # 9. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/robotperizia-frontend:latest'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      # Note: Next.js env vars are baked in at build time via --build-arg.
      # We don't need to set them as runtime env vars unless using SSR features that rely on them.

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-api-key/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-auth-domain/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-project-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-storage-bucket/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-messaging-sender-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-app-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/next-public-firebase-measurement-id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'


options:
  logging: CLOUD_LOGGING_ONLY
