steps:
  # 1. Build Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/robotperizia-backend', '.']
    dir: 'backend'

  # 2. Push Backend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/robotperizia-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/robotperizia-backend'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_REGION=europe-west1'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=perito-479708:europe-west1:robotperizia-db'
      - '--set-env-vars'
      - 'DB_USER=report_user'
      - '--set-env-vars'
      - 'DB_NAME=perizia_db'
      - '--set-env-vars'
      - 'STORAGE_BUCKET_NAME=robotperizia-uploads-roberto'
      - '--set-env-vars'
      - 'CLOUD_TASKS_QUEUE_PATH=projects/$PROJECT_ID/locations/europe-west1/queues/report-processing-queue'
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-account.json'
      - '--set-secrets'
      - '/secrets/service-account.json=firebase-creds:latest'
      - '--set-secrets'
      - 'DB_PASS=database-password:latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest'

  # 4. Get Backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run services describe robotperizia-backend --platform managed --region europe-west1 --format 'value(status.url)' > /workspace/backend_url.txt
        echo "Backend URL: $(cat /workspace/backend_url.txt)"

  # 5. Build Frontend Container (Injecting Backend URL)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/robotperizia-frontend \
        --build-arg NEXT_PUBLIC_API_URL=$(cat /workspace/backend_url.txt) \
        --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY \
        --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
        --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
        --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
        .
    dir: 'frontend'

  # 6. Push Frontend Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/robotperizia-frontend']

  # 7. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'robotperizia-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/robotperizia-frontend'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=REPLACE_ME_WITH_BUILD_ARG_IF_NEEDED_BUT_NEXTJS_NEEDS_BUILD_TIME' 
      # Note: Next.js bakes env vars at build time, so the docker build step handles it.
      # However, we can also set runtime env vars if using server-side rendering features.

substitutions:

  _NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyArgk92E56fnKcUmajrAdROu9BDxl7EQ2A"
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "perito-479708.firebaseapp.com"
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: "perito-479708"
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "perito-479708.firebasestorage.app"
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "738291935960"
  _NEXT_PUBLIC_FIREBASE_APP_ID: "1:738291935960:web:2fa811b15b4717c5ef05ad"
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-YVY6S4YY8K"

options:
  logging: CLOUD_LOGGING_ONLY
