"""optimize_schema_and_indexes

Revision ID: 19fc7bb876cb
Revises: g3b4c5d6e7f8
Create Date: 2025-12-04 14:48:34.102889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fc7bb876cb'
down_revision: Union[str, Sequence[str], None] = 'g3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allowed_emails', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'MEMBER', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'MEMBER'::userrole"),
               postgresql_using="role::userrole")
    op.alter_column('allowed_emails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # op.drop_index(op.f('idx_audit_logs_org_created'), table_name='audit_logs')
    # op.drop_index(op.f('idx_audit_logs_user'), table_name='audit_logs')
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'CLOSED', 'ARCHIVED', name='casestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::casestatus"),
               postgresql_using="status::casestatus")
    op.create_index('idx_cases_client', 'cases', ['organization_id', 'client_id'], unique=False)
    op.create_index('idx_cases_reference', 'cases', ['organization_id', 'reference_code'], unique=False)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_documents_case'), table_name='documents')
    op.create_index('idx_documents_case_status', 'documents', ['case_id', 'ai_status'], unique=False)
    op.create_index('idx_documents_org', 'documents', ['organization_id'], unique=False)
    op.alter_column('ml_training_pairs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # op.drop_index(op.f('idx_ml_pairs_case'), table_name='ml_training_pairs')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('outbox_messages', 'error_log',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_outbox_pending'), table_name='outbox_messages', postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index('idx_outbox_pending_fifo', 'outbox_messages', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.alter_column('report_versions', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('report_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # op.drop_constraint(op.f('uq_report_versions_case_ver'), 'report_versions', type_='unique')
    # op.drop_index(op.f('idx_users_org'), table_name='users')
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_index(op.f('idx_users_org'), 'users', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('uq_report_versions_case_ver'), 'report_versions', ['case_id', 'version_number'])
    op.alter_column('report_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('report_versions', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_outbox_pending_fifo', table_name='outbox_messages', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('idx_outbox_pending'), 'outbox_messages', ['created_at'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
    op.alter_column('outbox_messages', 'error_log',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('idx_ml_pairs_case'), 'ml_training_pairs', ['case_id'], unique=False)
    op.alter_column('ml_training_pairs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('idx_documents_org', table_name='documents')
    op.drop_index('idx_documents_case_status', table_name='documents')
    op.create_index(op.f('idx_documents_case'), 'documents', ['case_id'], unique=False)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('idx_cases_reference', table_name='cases')
    op.drop_index('idx_cases_client', table_name='cases')
    op.alter_column('cases', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'ARCHIVED', name='casestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::casestatus"))
    op.create_index(op.f('idx_audit_logs_user'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_org_created'), 'audit_logs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('allowed_emails', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('allowed_emails', 'role',
               existing_type=sa.Enum('ADMIN', 'MEMBER', name='userrole'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'MEMBER'::userrole"))
    # ### end Alembic commands ###
