"""Initial migration

Revision ID: be5bfcaa2399
Revises: 
Create Date: 2025-12-01 11:41:46.331544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be5bfcaa2399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered to satisfy Foreign Key constraints (Drop children first)
    op.drop_table('document_log')
    op.drop_index(op.f('ix_report_log_user_id'), table_name='report_log')
    op.drop_table('report_log')
    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', name='userrole'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('user_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('document_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stored_filepath', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extraction_status', postgresql.ENUM('SUCCESS', 'ERROR', 'SKIPPED', 'PROCESSING', name='extractionstatus'), autoincrement=False, nullable=True),
    sa.Column('extracted_content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('extraction_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report_log.id'], name=op.f('document_log_report_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_log_pkey'))
    )
    op.create_table('report_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'ERROR', 'PROCESSING', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('generation_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('api_cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress_logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prompt_token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidates_token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cached_content_token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_raw_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_report_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_docx_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('report_log_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('report_log_pkey'))
    )
    op.create_index(op.f('ix_report_log_user_id'), 'report_log', ['user_id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey'))
    )
    # ### end Alembic commands ###
